pom.xml
Remove unused dependency in pom.xml
=> Remove unused dependency in pom.xml

src/main/scala/org/apache/spark/shuffle/RssShuffleWriter.scala, src/main/scala/org/apache/spark/shuffle/rss/RssUtils.scala, src/test/scala/org/apache/spark/shuffle/RssShuffleManagerTest.scala
Sync latest code - fill real partition size in MapStatus
R: @boy-uber @mabansal
=> Sync latest code - fill real partition size in MapStatus

src/main/java/com/uber/rss/StreamServer.java, src/main/java/com/uber/rss/StreamServerConfig.java, src/main/java/com/uber/rss/execution/ExecutorShuffleStageState.java, src/main/java/com/uber/rss/execution/ShuffleExecutor.java, src/main/java/com/uber/rss/execution/ShufflePartitionWriter.java, src/main/java/com/uber/rss/handlers/UploadChannelInboundHandler.java, src/main/java/com/uber/rss/storage/ShuffleFileOutputStream.java, src/main/java/com/uber/rss/storage/ShuffleOutputStream.java, src/main/java/com/uber/rss/tools/StreamServerStressTool.java, src/main/java/com/uber/rss/tools/StreamServerStressToolLongRun.java, src/main/scala/org/apache/spark/shuffle/rss/RssStressTool.scala, src/test/java/com/uber/rss/execution/ShuffleExecutorTest.java, src/test/java/com/uber/rss/testutil/RssZookeeperCluster.java
Sync latest code, clean up: Remove unused configs and flush/flush, Mark stage as unsaved when there is new upload, Move logging out of lock
=> Sync latest code, clean up: Remove unused configs and flush/flush

src/main/java/com/uber/rss/handlers/UploadServerHandler.java
=> Removing Network codec

src/main/java/com/uber/rss/StreamServer.java, src/main/java/com/uber/rss/clients/ClientConstants.java, src/main/java/com/uber/rss/handlers/UploadChannelManager.java
=> Cleaning up channel manager

src/main/java/com/uber/rss/clients/DataBlockSocketReadClient.java, src/main/java/com/uber/rss/clients/PlainShuffleDataSocketReadClient.java, src/main/java/com/uber/rss/clients/PlainShuffleDataSyncWriteClient.java, src/main/java/com/uber/rss/clients/ShuffleDataSocketReadClient.java, src/main/java/com/uber/rss/decoders/StreamServerVersionDecoder.java, src/main/java/com/uber/rss/handlers/ChannelFutureCloseListener.java, src/main/java/com/uber/rss/handlers/ChannelIdleCheck.java, src/main/java/com/uber/rss/handlers/DownloadChannelInboundHandler.java, src/main/java/com/uber/rss/handlers/DownloadServerHandler.java, src/main/java/com/uber/rss/handlers/UploadChannelInboundHandler.java, src/main/scala/org/apache/spark/shuffle/RssOpts.scala, src/main/scala/org/apache/spark/shuffle/rss/WriterBufferManager.scala, src/test/java/com/uber/rss/testutil/TestStreamServer.java, src/test/scala/org/apache/spark/shuffle/rss/WriteBufferManagerTest.scala
Sync latest code: Close connection on exception in shuffle data read client, Close download server connection when receive close message
=> Sync latest code: Close connection on exception in shuffle data read client, Close download server connection when receive close message

src/main/java/com/uber/rss/clients/ServerBusyRetriableWriteClient.java, src/main/java/com/uber/rss/clients/StreamDecoderBase.java, src/main/java/com/uber/rss/messages/ConnectDownloadRequestMessage.java, src/main/java/com/uber/rss/messages/GetDataAvailabilityRequestMessage.java, src/main/java/com/uber/rss/messages/MessageConstants.java, src/test/java/com/uber/rss/clients/DownloadRequestClient.java, src/test/java/com/uber/rss/clients/WriteClientEdgeCaseTest.java
Adding client which can retry as well as adding the downloading message
=> Adding client which can retry as well as adding downloading message

src/main/java/com/uber/rss/clients/BlockingQueueReadClient.java, src/main/java/com/uber/rss/clients/BlockingShuffleDataReader.java, src/main/java/com/uber/rss/clients/BlockingSingleServerReadClient.java, src/main/java/com/uber/rss/clients/EofRecordKeyValuePair.java, src/main/java/com/uber/rss/clients/FailedFetchRecordKeyValuePair.java, src/main/java/com/uber/rss/clients/TaskByteArrayDataBlock.java, src/main/java/com/uber/rss/metadata/ServiceRegistryUtils.java, src/main/scala/org/apache/spark/shuffle/RssShuffleManager.scala, src/main/scala/org/apache/spark/shuffle/rss/BlockDownloaderPartitionRangeRecordIterator.scala, src/test/java/com/uber/rss/clients/BlockingServerReadClientTest.java
We need to create the blocking read clients as well as blocing protocols
=> Adding blocking clients to read the data asynchronously with blocking protocol messages

src/main/java/com/uber/rss/clients/RecordSocketReadClient.java, src/test/java/com/uber/rss/clients/ShuffleDataSocketReadClientTest.java
Adding socket read client which can read shuffle record as well adding test for that
=> Adding socket read client which can read shuffle record as well adding test for that

README.md, src/main/java/com/uber/rss/common/MemoryMonitor.java, src/main/java/com/uber/rss/decoders/StreamServerMessageDecoder.java, src/main/java/com/uber/rss/handlers/DownloadServerHandler.java, src/main/java/com/uber/rss/handlers/UploadChannelInboundHandler.java, src/main/java/com/uber/rss/metrics/M3Stats.java, src/main/java/com/uber/rss/metrics/ServerHandlerMetrics.java, src/main/java/com/uber/rss/storage/ShuffleFileOutputStream.java, src/main/java/com/uber/rss/tools/StreamServerStressTool.java
Revert the metrics name to fix the production dashboards
=> Revert the metrics name to fix the production dashboards

pom.xml
RSS-K8: Changing the POM file and modifying dependencies to be able to built the K8 branch
=> RSS-k8: Fixing the build failures in k8 branch

README.md, src/main/java/com/uber/rss/StreamServer.java, src/test/scala/org/apache/spark/shuffle/TestUtil.scala
We need to discover the RSS server, in this diff we are adding an environment variable to discover that.
=> RSS-K8: Adding environment variable to get the RSS server in K8 environment

src/main/java/com/uber/rss/RssBuildInfo.java, src/main/java/com/uber/rss/StreamServer.java, src/main/java/com/uber/rss/StreamServerConfig.java
=> Initial commit for Sprak 3.2 for K8

src/main/java/com/uber/rss/clients/BusyStatusSocketClient.java, src/main/java/com/uber/rss/clients/ClientBase.java, src/main/java/com/uber/rss/clients/ClientConstants.java, src/main/java/com/uber/rss/clients/ClientRetryOptions.java, src/main/java/com/uber/rss/clients/DataBlockSocketReadClient.java, src/main/java/com/uber/rss/clients/DataBlockSyncWriteClient.java
Adding Data block clients for k8
=> Adding Data block clients for k8

src/main/java/com/uber/rss/clients/HeartbeatSocketClient.java, src/main/java/com/uber/rss/clients/MultiServerAsyncWriteClient.java
Adding multi sever async client
=> Adding multi sever async client

src/main/java/com/uber/rss/clients/MultiServerHeartbeatClient.java, src/main/java/com/uber/rss/clients/MultiServerReadClient.java, src/main/java/com/uber/rss/clients/MultiServerSocketReadClient.java, src/main/java/com/uber/rss/clients/MultiServerSyncWriteClient.java
Adding multi server read and write client for K8
=> Adding multi server read and write client for K8

src/main/java/com/uber/rss/clients/MultiServerWriteClient.java, src/main/java/com/uber/rss/clients/NotifyClient.java, src/test/java/com/uber/rss/clients/MultiServerSyncWriteClientTest.java, src/test/java/com/uber/rss/clients/NotifyClientTest.java
Adding multi server write client for K8
=> Adding multi server write client for K8

src/main/java/com/uber/rss/clients/PlainShuffleDataSocketReadClient.java, src/main/java/com/uber/rss/clients/PlainShuffleDataSyncWriteClient.java, src/main/java/com/uber/rss/clients/PooledShuffleDataSyncWriteClient.java, src/main/java/com/uber/rss/clients/PooledWriteClientFactory.java, src/test/java/com/uber/rss/clients/PooledWriteClientFactoryRandomTest.java, src/test/java/com/uber/rss/clients/PooledWriteClientFactoryTest.java
Adding suuport for pooled write client for K8
=> Adding suuport for pooled write client for K8

src/main/java/com/uber/rss/clients/ReadClientDataOptions.java, src/main/java/com/uber/rss/clients/RegistryClient.java, src/test/java/com/uber/rss/clients/RegistryClientTest.java
=> Adding Registry client for K8

src/main/java/com/uber/rss/clients/ReplicatedReadClient.java, src/main/java/com/uber/rss/clients/ReplicatedWriteClient.java, src/test/java/com/uber/rss/clients/ReplicatedReadClientTest.java, src/test/java/com/uber/rss/clients/ReplicatedWriteClientTest.java
Adding support for K8 in replicate read and write clients
=> Adding support for K8 in replicate read and write clients

src/main/java/com/uber/rss/clients/RetriableSocketReadClient.java, src/main/java/com/uber/rss/clients/ServerConnectionStringCache.java, src/main/java/com/uber/rss/clients/ServerConnectionStringResolver.java, src/test/java/com/uber/rss/clients/RetriableSocketReadClientTest.java
adding K8 support for retriable read client
=> adding K8 support for retriable read client

src/main/java/com/uber/rss/clients/ServerIdAwareSocketReadClient.java, src/main/java/com/uber/rss/clients/ServerIdAwareSyncWriteClient.java, src/test/java/com/uber/rss/clients/ServerIdAwareSocketReadClientTest.java, src/test/java/com/uber/rss/clients/ServerIdAwareSyncWriteClientTest.java
Adding k8 support for server side id aware read and write clients
=> Adding k8 support for server side id aware read and write clients
